apiVersion: v1
kind: Service
metadata:
  name: jaeger-internal
  namespace: default
spec:
 # clusterIP: 10.110.12.241
  ports:
  - name: "5775"
    port: 5775
    protocol: UDP
    targetPort: 5775
  - name: "6831"
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: "6832"
    port: 6832
    protocol: UDP
    targetPort: 6832
  - name: "5778"
    port: 5778
    protocol: TCP
    targetPort: 5778
  - name: "14268"
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: "9411"
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    service: jaeger
  sessionAffinity: None
  type: ClusterIP
