apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: socialnetwork
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-09-02T12:06:23Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: jaeger
  namespace: default
  resourceVersion: "5375"
  uid: 8d65e396-ad55-46f3-b55c-55c7c6439669
spec:
  #clusterIP: 10.176.4.212
  #clusterIPs:
  #- 10.176.4.212
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "5775"
    port: 5775
    protocol: UDP
    targetPort: 5775
  - name: "6831"
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: "6832"
    port: 6832
    protocol: UDP
    targetPort: 6832
  - name: "5778"
    port: 5778
    protocol: TCP
    targetPort: 5778
  - name: "16686"
    port: 16686
    protocol: TCP
    targetPort: 16686
  - name: "14268"
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: "9411"
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    service: jaeger
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
