apiVersion: v1
kind: Service
metadata:
  name: jaeger-external
  namespace: default
spec:
  ports:
  - name: "16686"
    port: 16686
    protocol: TCP
    targetPort: 16686
    nodePort: 31686
  selector:
    service: jaeger
  sessionAffinity: None
  type: NodePort
