# TeaStore Workload Config
BENCHMARK='TEA'
WEBUI="http://econome-4.nantes.grid5000.fr:30080"
PROMETHEUS_URL="http://econome-4.nantes.grid5000.fr:30090"
DURATION=5
STEP=1
NAMESPACE="default"


#Directories and files
WARMUP_FILE="/warmUp/constant_10.csv"


#Deployment files

CERTIFICATE="admin_kube5k.conf"
LOAD_DIRECTORY=""

#_profiles_sequentially_train_load_1cpu
PATH_SUFFIX='_profiles_sequentially_train_load_no_limit'
# Manifests

APP_MANIFEST="gricard-teastore-2.yaml"

