# TeaStore Workload Config
BENCHMARK='TEA'
WEBUI="http://econome-22.nantes.grid5000.fr:30080"
PROMETHEUS_URL="http://econome-22.nantes.grid5000.fr:30090"
DURATION=5
STEP=1
NAMESPACE="default"


#Directories and files
WARMUP_FILE="/warmUp/constant_10.csv"


#Deployment files

CERTIFICATE="admin_collect-data.conf"
LOAD_DIRECTORY=""

PATH_SUFFIX='_sequential_train_50_1cpu'
# Manifests

APP_MANIFEST="gricard-teastore_cpu_1.yaml"