# TeaStore Workload Config
BENCHMARK='TEA'
WEBUI="http://econome-5.nantes.grid5000.fr:32677"
PROMETHEUS_URL="http://econome-5.nantes.grid5000.fr:30569"
DURATION=5
STEP=1
NAMESPACE="default"

#Directories and files
#currently it's done without warmup
WARMUP_FILE="/warmUp/const_linear_30requests_per_sec.csv"

PATH_SUFFIX='profile_login_workload'

#Deployment files

CERTIFICATE="admin_collect-data.conf"
LOAD_DIRECTORY=""
