# TeaStore Workload Config
BENCHMARK='TEA'
WEBUI="http://econome-20.nantes.grid5000.fr:32677"
PROMETHEUS_URL="http://econome-20.nantes.grid5000.fr:30090"
DURATION=5
STEP=1
NAMESPACE="default"


#Directories and files
WARMUP_FILE="/warmUp/const_linear_30requests_per_sec.csv"


#Deployment files

CERTIFICATE=""
LOAD_DIRECTORY=""
