# TeaStore Workload Config
BENCHMARK='TEA'
WEBUI="http://econome-9.nantes.grid5000.fr:32677"
PROMETHEUS_URL="http://econome-9.nantes.grid5000.fr:30090"
DURATION=5
STEP=1
NAMESPACE="default"

#Directories and files
#currently it's done without warmup
WARMUP_FILE="/warmUp/const_linear_30requests_per_sec.csv"

PATH_SUFFIX='30s_collect_warmup_load1'

#Deployment files

CERTIFICATE="admin_collect-data.conf"
LOAD_DIRECTORY=""

#TASK=("HomePage")
TASK=("SearchTicket" "BookTicket" "ConsignTicket")

