apiVersion: monitoring.coreos.com/v2
kind: ServiceMonitor
metadata:
  name: prometheus-oper-linkerd-proxy
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  jobLabel: linkerd-proxy
  selector:
    matchLabels:
      app: linkerd
  namespaceSelector:
    matchNames:
      - linkerd
  endpoints:
    - port: linkerd-admin
      interval: 15s
      relabelings:
        - sourceLabels: [ __meta_kubernetes_pod_container_name, __meta_kubernetes_pod_container_port_name, __meta_kubernetes_pod_label_linkerd_io_control_plane_ns ]
          action: keep
          regex: ^linkerd-proxy;linkerd-admin;linkerd$
        - sourceLabels: [ __meta_kubernetes_namespace ]
          action: replace
          target_label: namespace
        - sourceLabels: [ __meta_kubernetes_pod_name ]
          action: replace
          target_label: pod
        - sourceLabels: [ __meta_kubernetes_pod_label_linkerd_io_proxy_job ]
          action: replace
          target_label: k8s_job
