apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: app-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.136.17.251-10.136.17.253
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system